CREATE TABLE IF NOT EXISTS autores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS livros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    autor_id BIGINT NOT NULL,
    CONSTRAINT fk_autor FOREIGN KEY (autor_id) REFERENCES autores(id)
);


-- Autores iniciais
INSERT INTO autores (nome, email) VALUES
('Machado de Assis', 'machado@literatura.com'),
('Clarice Lispector', 'clarice@literatura.com'),
('Jorge Amado', 'jorge@literatura.com'),
('José de Alencar', 'alencar@literatura.com'),
('Graciliano Ramos', 'graciliano@literatura.com'),
('Rachel de Queiroz', 'rachel@literatura.com'),
('Cecília Meireles', 'cecilia@literatura.com'),
('Carlos Drummond de Andrade', 'drummond@literatura.com'),
('Monteiro Lobato', 'lobato@literatura.com'),
('Lima Barreto', 'lima@literatura.com');

-- Livros iniciais
INSERT INTO livros (titulo, isbn, autor_id) VALUES
('Dom Casmurro', '978-85-01-00001-0', 1),
('Memórias Póstumas de Brás Cubas', '978-85-01-00004-1', 1),
('A Hora da Estrela', '978-85-01-00002-7', 2),
('Laços de Família', '978-85-01-00005-8', 2),
('Capitães da Areia', '978-85-01-00003-4', 3),
('Gabriela, Cravo e Canela', '978-85-01-00006-5', 3),
('Iracema', '978-85-01-00007-2', 4),
('O Guarani', '978-85-01-00008-9', 4),
('Vidas Secas', '978-85-01-00009-6', 5),
('São Bernardo', '978-85-01-00010-2', 5),
('O Quinze', '978-85-01-00011-9', 6),
('As Três Marias', '978-85-01-00012-6', 6),
('Romanceiro da Inconfidência', '978-85-01-00013-3', 7),
('Viagem', '978-85-01-00014-0', 7),
('Alguma Poesia', '978-85-01-00015-7', 8),
('Sentimento do Mundo', '978-85-01-00016-4', 8),
('Reinações de Narizinho', '978-85-01-00017-1', 9),
('O Sítio do Picapau Amarelo', '978-85-01-00018-8', 9),
('Triste Fim de Policarpo Quaresma', '978-85-01-00019-5', 10),
('Clara dos Anjos', '978-85-01-00020-1', 10);
