-- ==============================
-- TABELA: AUTORES
-- ==============================
CREATE TABLE IF NOT EXISTS autores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    biografia VARCHAR(1000),
    data_nascimento DATE,
    nacionalidade VARCHAR(60)
);

-- ==============================
-- TABELA: LIVROS
-- ==============================
CREATE TABLE IF NOT EXISTS livros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    genero VARCHAR(50) NOT NULL,
    editora VARCHAR(100),
    paginas INT CHECK (paginas > 0),
    ano_publicacao INT CHECK (ano_publicacao >= 1500 AND ano_publicacao <= 2025),
    preco DECIMAL(10,2) CHECK (preco > 0),
    descricao VARCHAR(1000),
    autor_id BIGINT NOT NULL,
    CONSTRAINT fk_autor FOREIGN KEY (autor_id) REFERENCES autores(id)
);


-- ====================================================
-- DADOS DE EXEMPLO - AUTORES E LIVROS
-- ====================================================

-- ========================
-- AUTORES
-- ========================

INSERT INTO autores (nome, email, biografia, data_nascimento, nacionalidade)
VALUES ('Machado de Assis', 'machado@literatura.com',
        'Considerado um dos maiores escritores brasileiros, fundador da Academia Brasileira de Letras.',
        '1839-06-21', 'Brasileiro');

INSERT INTO autores (nome, email, biografia, data_nascimento, nacionalidade)
VALUES ('Clarice Lispector', 'clarice@literatura.com',
        'Reconhecida pela escrita introspectiva e inovadora, autora de A Hora da Estrela.',
        '1920-12-10', 'Brasileira');

INSERT INTO autores (nome, email, biografia, data_nascimento, nacionalidade)
VALUES ('Jorge Amado', 'jorge@literatura.com',
        'Um dos escritores mais populares do Brasil, conhecido por retratar o povo baiano.',
        '1912-08-10', 'Brasileiro');

INSERT INTO autores (nome, email, biografia, data_nascimento, nacionalidade)
VALUES ('Rachel de Queiroz', 'rachel@literatura.com',
        'Primeira mulher a ingressar na Academia Brasileira de Letras, autora de O Quinze.',
        '1910-11-17', 'Brasileira');

INSERT INTO autores (nome, email, biografia, data_nascimento, nacionalidade)
VALUES ('Carlos Drummond de Andrade', 'drummond@literatura.com',
        'Poeta mineiro e cronista, considerado o maior poeta brasileiro do século XX.',
        '1902-10-31', 'Brasileiro');

-- ========================
-- LIVROS
-- ========================

INSERT INTO livros (titulo, isbn, genero, editora, paginas, ano_publicacao, preco, descricao, autor_id)
VALUES ('Dom Casmurro', '978-85-01-00001-0', 'Romance', 'Editora Globo', 256, 1899, 39.90,
        'A clássica história de Bentinho e Capitu.', 1);

INSERT INTO livros (titulo, isbn, genero, editora, paginas, ano_publicacao, preco, descricao, autor_id)
VALUES ('A Hora da Estrela', '978-85-01-00002-7', 'Romance', 'Rocco', 96, 1977, 29.90,
        'A história de Macabéa, uma nordestina no Rio de Janeiro.', 2);

INSERT INTO livros (titulo, isbn, genero, editora, paginas, ano_publicacao, preco, descricao, autor_id)
VALUES ('Capitães da Areia', '978-85-01-00003-4', 'Romance', 'Companhia das Letras', 272, 1937, 37.50,
        'A vida de meninos de rua em Salvador.', 3);

INSERT INTO livros (titulo, isbn, genero, editora, paginas, ano_publicacao, preco, descricao, autor_id)
VALUES ('O Quinze', '978-85-01-00011-9', 'Romance Regionalista', 'José Olympio', 208, 1930, 29.50,
        'A seca de 1915 no sertão nordestino.', 4);

INSERT INTO livros (titulo, isbn, genero, editora, paginas, ano_publicacao, preco, descricao, autor_id)
VALUES ('Sentimento do Mundo', '978-85-01-00016-4', 'Poesia', 'Companhia das Letras', 144, 1940, 27.00,
        'Poesias sobre o homem e o mundo moderno.', 5);

