CREATE TABLE IF NOT EXISTS autores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS livros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    autor_id BIGINT NOT NULL,
    CONSTRAINT fk_autor FOREIGN KEY (autor_id) REFERENCES autores(id)
);


-- Autores iniciais
INSERT INTO autores (nome, email) VALUES
('Machado de Assis', 'machado@literatura.com'),
('Clarice Lispector', 'clarice@literatura.com'),
('Jorge Amado', 'jorge@literatura.com');

-- Livros iniciais
INSERT INTO livros (titulo, isbn, autor_id) VALUES
('Dom Casmurro', '978-85-01-00001-0', 1),
('A Hora da Estrela', '978-85-01-00002-7', 2),
('Capitães da Areia', '978-85-01-00003-4', 3);
